server:
  port: 8082
  servlet:
    context-path: /demo
spring:
  application:
    name: teste-cics

cics:
  host: 10.0.10.129 #10.234.30.1
  porta: 2006
  protocolo: tcp
  serverName: CICSHML

  
#host da alta (programa do antonio)
#  https://homologacaosistemas.casasbahia.com.br/JavaCTGCics/CicsServlet
#  10.0.10.129 
